name: CI
on:
  push:
    branches:
    - develop
    - master
    - 0.2.x
  pull_request:
    branches:
    - develop
    - master
    - 0.2.x
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [8.x, 11.x, 13.x]  
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Unit Tests
      if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
      run: mvn -V test
    - name: Unit Tests with Coverage
      if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
      run: |
        mvn -V org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report
    - name: Check Report
      if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && startsWith(env.JAVA_HOME, '/opt/hostedtoolcache/jdk/8')
      run: |
        set -e
        env | sort
        ls -la target/site/jacoco/jacoco.xml